export const trilhas = [
  {
    'nome': 'Python',
    'area': 'Back-end',
    'qtdAulas': 20,
    'qtdExercicios': 50,
    'logo': require('../../assets/logo/trilhas/python-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao python'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao python'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
      {'number': 46, 'description': ''},
      {'number': 47, 'description': ''},
      {'number': 48, 'description': ''},
      {'number': 49, 'description': ''},
      {'number': 50, 'description': ''},
    ],
  },
  {
    'nome': 'JavaScript',
    'area': 'Front-end',
    'qtdAulas': 30,
    'qtdExercicios': 60,
    'logo': require('../../assets/logo/trilhas/javascript-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
      {'number': 46, 'description': ''},
      {'number': 47, 'description': ''},
      {'number': 48, 'description': ''},
      {'number': 49, 'description': ''},
      {'number': 50, 'description': ''},
      {'number': 51, 'description': ''},
      {'number': 52, 'description': ''},
      {'number': 53, 'description': ''},
      {'number': 54, 'description': ''},
      {'number': 55, 'description': ''},
      {'number': 56, 'description': ''},
      {'number': 57, 'description': ''},
      {'number': 58, 'description': ''},
      {'number': 59, 'description': ''},
      {'number': 60, 'description': ''},
    ],
  },
  {
    'nome': 'TypeScript',
    'area': 'Front-end',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/typescript-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'Ruby',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/ruby-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'Golang',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/golang-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'Swift',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/swift-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'Kotlin',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/kotlin-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'C',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/c-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'C#',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/csharp-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  },
  {
    'nome': 'Java',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/java-logo.png'),
    'aulas' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'description': 'Introdução ao javascript'},
      {'number': 2, 'description': 'A'},
      {'number': 3, 'description': 'B'},
      {'number': 4, 'description': 'C'},
      {'number': 5, 'description': 'D'},
      {'number': 6, 'description': 'E'},
      {'number': 7, 'description': ''},
      {'number': 8, 'description': ''},
      {'number': 9, 'description': ''},
      {'number': 10, 'description': ''},
      {'number': 11, 'description': ''},
      {'number': 12, 'description': ''},
      {'number': 13, 'description': ''},
      {'number': 14, 'description': ''},
      {'number': 15, 'description': ''},
      {'number': 16, 'description': ''},
      {'number': 17, 'description': ''},
      {'number': 18, 'description': ''},
      {'number': 19, 'description': ''},
      {'number': 20, 'description': ''},
      {'number': 21, 'description': ''},
      {'number': 22, 'description': ''},
      {'number': 23, 'description': ''},
      {'number': 24, 'description': ''},
      {'number': 25, 'description': ''},
      {'number': 26, 'description': ''},
      {'number': 27, 'description': ''},
      {'number': 28, 'description': ''},
      {'number': 29, 'description': ''},
      {'number': 30, 'description': ''},
      {'number': 31, 'description': ''},
      {'number': 32, 'description': ''},
      {'number': 33, 'description': ''},
      {'number': 34, 'description': ''},
      {'number': 35, 'description': ''},
      {'number': 36, 'description': ''},
      {'number': 37, 'description': ''},
      {'number': 38, 'description': ''},
      {'number': 39, 'description': ''},
      {'number': 40, 'description': ''},
      {'number': 41, 'description': ''},
      {'number': 42, 'description': ''},
      {'number': 43, 'description': ''},
      {'number': 44, 'description': ''},
      {'number': 45, 'description': ''},
    ],
  }
];