export const trilhas = [
  {
    'nome': 'Python',
    'area': 'Back-end',
    'qtdAulas': 20,
    'qtdExercicios': 50,
    'logo': require('../../assets/logo/trilhas/python-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao python'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao python'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
      {'index': 46, 'title': ''},
      {'index': 47, 'title': ''},
      {'index': 48, 'title': ''},
      {'index': 49, 'title': ''},
      {'index': 50, 'title': ''},
    ],
  },
  {
    'nome': 'JavaScript',
    'area': 'Front-end',
    'qtdAulas': 30,
    'qtdExercicios': 60,
    'logo': require('../../assets/logo/trilhas/javascript-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
      {'index': 46, 'title': ''},
      {'index': 47, 'title': ''},
      {'index': 48, 'title': ''},
      {'index': 49, 'title': ''},
      {'index': 50, 'title': ''},
      {'index': 51, 'title': ''},
      {'index': 52, 'title': ''},
      {'index': 53, 'title': ''},
      {'index': 54, 'title': ''},
      {'index': 55, 'title': ''},
      {'index': 56, 'title': ''},
      {'index': 57, 'title': ''},
      {'index': 58, 'title': ''},
      {'index': 59, 'title': ''},
      {'index': 60, 'title': ''},
    ],
  },
  {
    'nome': 'TypeScript',
    'area': 'Front-end',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/typescript-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'Ruby',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/ruby-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'Golang',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/golang-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'Swift',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/swift-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'Kotlin',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/kotlin-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'C',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/c-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'C#',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/csharp-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  },
  {
    'nome': 'Java',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/java-logo.png'),
    'aulas' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'title': 'Introdução ao javascript'},
      {'index': 2, 'title': 'A'},
      {'index': 3, 'title': 'B'},
      {'index': 4, 'title': 'C'},
      {'index': 5, 'title': 'D'},
      {'index': 6, 'title': 'E'},
      {'index': 7, 'title': ''},
      {'index': 8, 'title': ''},
      {'index': 9, 'title': ''},
      {'index': 10, 'title': ''},
      {'index': 11, 'title': ''},
      {'index': 12, 'title': ''},
      {'index': 13, 'title': ''},
      {'index': 14, 'title': ''},
      {'index': 15, 'title': ''},
      {'index': 16, 'title': ''},
      {'index': 17, 'title': ''},
      {'index': 18, 'title': ''},
      {'index': 19, 'title': ''},
      {'index': 20, 'title': ''},
      {'index': 21, 'title': ''},
      {'index': 22, 'title': ''},
      {'index': 23, 'title': ''},
      {'index': 24, 'title': ''},
      {'index': 25, 'title': ''},
      {'index': 26, 'title': ''},
      {'index': 27, 'title': ''},
      {'index': 28, 'title': ''},
      {'index': 29, 'title': ''},
      {'index': 30, 'title': ''},
      {'index': 31, 'title': ''},
      {'index': 32, 'title': ''},
      {'index': 33, 'title': ''},
      {'index': 34, 'title': ''},
      {'index': 35, 'title': ''},
      {'index': 36, 'title': ''},
      {'index': 37, 'title': ''},
      {'index': 38, 'title': ''},
      {'index': 39, 'title': ''},
      {'index': 40, 'title': ''},
      {'index': 41, 'title': ''},
      {'index': 42, 'title': ''},
      {'index': 43, 'title': ''},
      {'index': 44, 'title': ''},
      {'index': 45, 'title': ''},
    ],
  }
];