export const yourProgress = [
  {
    'nome': 'Python',
    'area': 'Back-end',
    'qtdAulas': 20,
    'qtdExercicios': 50,
    'logo': require('../../assets/logo/trilhas/python-logo.png'),
    'aulas' : [
      {'index': 1, 'status': 'done', 'title': 'Introdução ao python'},
      {'index': 2, 'status': 'done', 'title': 'A'},
      {'index': 3, 'status': 'done', 'title': 'B'},
      {'index': 4, 'status': 'done', 'title': 'C'},
      {'index': 5, 'status': 'done', 'title': 'D'},
      {'index': 6, 'status': 'done', 'title': 'E'},
      {'index': 7, 'status': 'done', 'title': ''},
      {'index': 8, 'status': 'done', 'title': ''},
      {'index': 9, 'status': 'done', 'title': ''},
      {'index': 10, 'status': 'done', 'title': ''},
      {'index': 11, 'status': 'progress', 'title': ''},
      {'index': 12, 'status': 'progress', 'title': ''},
      {'index': 13, 'status': 'progress', 'title': ''},
      {'index': 14, 'status': 'progress', 'title': ''},
      {'index': 15, 'status': 'progress', 'title': ''},
      {'index': 16, 'status': 'progress', 'title': ''},
      {'index': 17, 'status': 'progress', 'title': ''},
      {'index': 18, 'status': 'progress', 'title': ''},
      {'index': 19, 'status': 'progress', 'title': ''},
      {'index': 20, 'status': 'progress', 'title': ''},
      {'index': 21, 'status': 'progress', 'title': ''},
      {'index': 22, 'status': 'progress', 'title': ''},
      {'index': 23, 'status': 'progress', 'title': ''},
      {'index': 24, 'status': 'progress', 'title': ''},
      {'index': 25, 'status': 'progress', 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'status': 'done', 'title': 'Introdução ao python'},
      {'index': 2, 'status': 'done', 'title': 'A'},
      {'index': 3, 'status': 'done', 'title': 'B'},
      {'index': 4, 'status': 'done', 'title': 'C'},
      {'index': 5, 'status': 'done', 'title': 'D'},
      {'index': 6, 'status': 'done', 'title': 'E'},
      {'index': 7, 'status': 'done', 'title': ''},
      {'index': 8, 'status': 'done', 'title': ''},
      {'index': 9, 'status': 'done', 'title': ''},
      {'index': 10, 'status': 'done', 'title': ''},
      {'index': 11, 'status': 'done', 'title': ''},
      {'index': 12, 'status': 'done', 'title': ''},
      {'index': 13, 'status': 'done', 'title': ''},
      {'index': 14, 'status': 'done', 'title': ''},
      {'index': 15, 'status': 'done', 'title': ''},
      {'index': 16, 'status': 'done', 'title': ''},
      {'index': 17, 'status': 'done', 'title': ''},
      {'index': 18, 'status': 'done', 'title': ''},
      {'index': 19, 'status': 'done', 'title': ''},
      {'index': 20, 'status': 'done', 'title': ''},
      {'index': 21, 'status': 'done', 'title': ''},
      {'index': 22, 'status': 'done', 'title': ''},
      {'index': 23, 'status': 'done', 'title': ''},
      {'index': 24, 'status': 'done', 'title': ''},
      {'index': 25, 'status': 'done', 'title': ''},
      {'index': 26, 'status': 'progress', 'title': ''},
      {'index': 27, 'status': 'progress', 'title': ''},
      {'index': 28, 'status': 'progress', 'title': ''},
      {'index': 29, 'status': 'progress', 'title': ''},
      {'index': 30, 'status': 'progress', 'title': ''},
      {'index': 31, 'status': 'progress', 'title': ''},
      {'index': 32, 'status': 'progress', 'title': ''},
      {'index': 33, 'status': 'progress', 'title': ''},
      {'index': 34, 'status': 'progress', 'title': ''},
      {'index': 35, 'status': 'progress', 'title': ''},
      {'index': 36, 'status': 'progress', 'title': ''},
      {'index': 37, 'status': 'progress', 'title': ''},
      {'index': 38, 'status': 'progress', 'title': ''},
      {'index': 39, 'status': 'progress', 'title': ''},
      {'index': 40, 'status': 'progress', 'title': ''},
      {'index': 41, 'status': 'progress', 'title': ''},
      {'index': 42, 'status': 'progress', 'title': ''},
      {'index': 43, 'status': 'progress', 'title': ''},
      {'index': 44, 'status': 'progress', 'title': ''},
      {'index': 45, 'status': 'progress', 'title': ''},
      {'index': 46, 'status': 'progress', 'title': ''},
      {'index': 47, 'status': 'progress', 'title': ''},
      {'index': 48, 'status': 'progress', 'title': ''},
      {'index': 49, 'status': 'progress', 'title': ''},
      {'index': 50, 'status': 'progress', 'title': ''},

    ],
    'status': 'progress'
  },
  {
    'nome': 'Golang',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/golang-logo.png'),
    'aulas' : [
      {'index': 1, 'status': 'done', 'title': 'Introdução ao golang'},
      {'index': 2, 'status': 'done', 'title': 'A'},
      {'index': 3, 'status': 'done', 'title': 'B'},
      {'index': 4, 'status': 'done', 'title': 'C'},
      {'index': 5, 'status': 'done', 'title': 'D'},
      {'index': 6, 'status': 'done', 'title': 'E'},
      {'index': 7, 'status': 'done', 'title': ''},
      {'index': 8, 'status': 'done', 'title': ''},
      {'index': 9, 'status': 'done', 'title': ''},
      {'index': 10, 'status': 'done', 'title': ''},
      {'index': 11, 'status': 'done', 'title': ''},
      {'index': 12, 'status': 'done', 'title': ''},
      {'index': 13, 'status': 'done', 'title': ''},
      {'index': 14, 'status': 'done', 'title': ''},
      {'index': 15, 'status': 'done', 'title': ''},
      {'index': 16, 'status': 'done', 'title': ''},
      {'index': 17, 'status': 'done', 'title': ''},
      {'index': 18, 'status': 'done', 'title': ''},
      {'index': 19, 'status': 'done', 'title': ''},
      {'index': 20, 'status': 'done', 'title': ''},
      {'index': 21, 'status': 'done', 'title': ''},
      {'index': 22, 'status': 'done', 'title': ''},
      {'index': 23, 'status': 'done', 'title': ''},
      {'index': 24, 'status': 'done', 'title': ''},
      {'index': 25, 'status': 'done', 'title': ''}
    ],
    'exercicios' : [
      {'index': 1, 'status': 'done', 'title': 'Introdução ao golang'},
      {'index': 2, 'status': 'done', 'title': 'A'},
      {'index': 3, 'status': 'done', 'title': 'B'},
      {'index': 4, 'status': 'done', 'title': 'C'},
      {'index': 5, 'status': 'done', 'title': 'D'},
      {'index': 6, 'status': 'done', 'title': 'E'},
      {'index': 7, 'status': 'done', 'title': ''},
      {'index': 8, 'status': 'done', 'title': ''},
      {'index': 9, 'status': 'done', 'title': ''},
      {'index': 10, 'status': 'done', 'title': ''},
      {'index': 11, 'status': 'done', 'title': ''},
      {'index': 12, 'status': 'done', 'title': ''},
      {'index': 13, 'status': 'done', 'title': ''},
      {'index': 14, 'status': 'done', 'title': ''},
      {'index': 15, 'status': 'done', 'title': ''},
      {'index': 16, 'status': 'done', 'title': ''},
      {'index': 17, 'status': 'done', 'title': ''},
      {'index': 18, 'status': 'done', 'title': ''},
      {'index': 19, 'status': 'done', 'title': ''},
      {'index': 20, 'status': 'done', 'title': ''},
      {'index': 21, 'status': 'done', 'title': ''},
      {'index': 22, 'status': 'done', 'title': ''},
      {'index': 23, 'status': 'done', 'title': ''},
      {'index': 24, 'status': 'done', 'title': ''},
      {'index': 25, 'status': 'done', 'title': ''}
    ],
    'status': 'done'
  },
];