export const yourProgress = [
  {
    'nome': 'Python',
    'area': 'Back-end',
    'qtdAulas': 20,
    'qtdExercicios': 50,
    'logo': require('../../assets/logo/trilhas/python-logo.png'),
    'aulas' : [
      {'number': 1, 'status': 'done', 'description': 'Introdução ao python'},
      {'number': 2, 'status': 'done', 'description': 'A'},
      {'number': 3, 'status': 'done', 'description': 'B'},
      {'number': 4, 'status': 'done', 'description': 'C'},
      {'number': 5, 'status': 'done', 'description': 'D'},
      {'number': 6, 'status': 'done', 'description': 'E'},
      {'number': 7, 'status': 'done', 'description': ''},
      {'number': 8, 'status': 'done', 'description': ''},
      {'number': 9, 'status': 'done', 'description': ''},
      {'number': 10, 'status': 'done', 'description': ''},
      {'number': 11, 'status': 'progress', 'description': ''},
      {'number': 12, 'status': 'progress', 'description': ''},
      {'number': 13, 'status': 'progress', 'description': ''},
      {'number': 14, 'status': 'progress', 'description': ''},
      {'number': 15, 'status': 'progress', 'description': ''},
      {'number': 16, 'status': 'progress', 'description': ''},
      {'number': 17, 'status': 'progress', 'description': ''},
      {'number': 18, 'status': 'progress', 'description': ''},
      {'number': 19, 'status': 'progress', 'description': ''},
      {'number': 20, 'status': 'progress', 'description': ''},
      {'number': 21, 'status': 'progress', 'description': ''},
      {'number': 22, 'status': 'progress', 'description': ''},
      {'number': 23, 'status': 'progress', 'description': ''},
      {'number': 24, 'status': 'progress', 'description': ''},
      {'number': 25, 'status': 'progress', 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'status': 'done', 'description': 'Introdução ao python'},
      {'number': 2, 'status': 'done', 'description': 'A'},
      {'number': 3, 'status': 'done', 'description': 'B'},
      {'number': 4, 'status': 'done', 'description': 'C'},
      {'number': 5, 'status': 'done', 'description': 'D'},
      {'number': 6, 'status': 'done', 'description': 'E'},
      {'number': 7, 'status': 'done', 'description': ''},
      {'number': 8, 'status': 'done', 'description': ''},
      {'number': 9, 'status': 'done', 'description': ''},
      {'number': 10, 'status': 'done', 'description': ''},
      {'number': 11, 'status': 'done', 'description': ''},
      {'number': 12, 'status': 'done', 'description': ''},
      {'number': 13, 'status': 'done', 'description': ''},
      {'number': 14, 'status': 'done', 'description': ''},
      {'number': 15, 'status': 'done', 'description': ''},
      {'number': 16, 'status': 'done', 'description': ''},
      {'number': 17, 'status': 'done', 'description': ''},
      {'number': 18, 'status': 'done', 'description': ''},
      {'number': 19, 'status': 'done', 'description': ''},
      {'number': 20, 'status': 'done', 'description': ''},
      {'number': 21, 'status': 'done', 'description': ''},
      {'number': 22, 'status': 'done', 'description': ''},
      {'number': 23, 'status': 'done', 'description': ''},
      {'number': 24, 'status': 'done', 'description': ''},
      {'number': 25, 'status': 'done', 'description': ''},
      {'number': 26, 'status': 'progress', 'description': ''},
      {'number': 27, 'status': 'progress', 'description': ''},
      {'number': 28, 'status': 'progress', 'description': ''},
      {'number': 29, 'status': 'progress', 'description': ''},
      {'number': 30, 'status': 'progress', 'description': ''},
      {'number': 31, 'status': 'progress', 'description': ''},
      {'number': 32, 'status': 'progress', 'description': ''},
      {'number': 33, 'status': 'progress', 'description': ''},
      {'number': 34, 'status': 'progress', 'description': ''},
      {'number': 35, 'status': 'progress', 'description': ''},
      {'number': 36, 'status': 'progress', 'description': ''},
      {'number': 37, 'status': 'progress', 'description': ''},
      {'number': 38, 'status': 'progress', 'description': ''},
      {'number': 39, 'status': 'progress', 'description': ''},
      {'number': 40, 'status': 'progress', 'description': ''},
      {'number': 41, 'status': 'progress', 'description': ''},
      {'number': 42, 'status': 'progress', 'description': ''},
      {'number': 43, 'status': 'progress', 'description': ''},
      {'number': 44, 'status': 'progress', 'description': ''},
      {'number': 45, 'status': 'progress', 'description': ''},
      {'number': 46, 'status': 'progress', 'description': ''},
      {'number': 47, 'status': 'progress', 'description': ''},
      {'number': 48, 'status': 'progress', 'description': ''},
      {'number': 49, 'status': 'progress', 'description': ''},
      {'number': 50, 'status': 'progress', 'description': ''},

    ],
    'status': 'progress'
  },
  {
    'nome': 'Golang',
    'qtdAulas': 25,
    'qtdExercicios': 45,
    'logo': require('../../assets/logo/trilhas/golang-logo.png'),
    'aulas' : [
      {'number': 1, 'status': 'done', 'description': 'Introdução ao golang'},
      {'number': 2, 'status': 'done', 'description': 'A'},
      {'number': 3, 'status': 'done', 'description': 'B'},
      {'number': 4, 'status': 'done', 'description': 'C'},
      {'number': 5, 'status': 'done', 'description': 'D'},
      {'number': 6, 'status': 'done', 'description': 'E'},
      {'number': 7, 'status': 'done', 'description': ''},
      {'number': 8, 'status': 'done', 'description': ''},
      {'number': 9, 'status': 'done', 'description': ''},
      {'number': 10, 'status': 'done', 'description': ''},
      {'number': 11, 'status': 'done', 'description': ''},
      {'number': 12, 'status': 'done', 'description': ''},
      {'number': 13, 'status': 'done', 'description': ''},
      {'number': 14, 'status': 'done', 'description': ''},
      {'number': 15, 'status': 'done', 'description': ''},
      {'number': 16, 'status': 'done', 'description': ''},
      {'number': 17, 'status': 'done', 'description': ''},
      {'number': 18, 'status': 'done', 'description': ''},
      {'number': 19, 'status': 'done', 'description': ''},
      {'number': 20, 'status': 'done', 'description': ''},
      {'number': 21, 'status': 'done', 'description': ''},
      {'number': 22, 'status': 'done', 'description': ''},
      {'number': 23, 'status': 'done', 'description': ''},
      {'number': 24, 'status': 'done', 'description': ''},
      {'number': 25, 'status': 'done', 'description': ''}
    ],
    'exercicios' : [
      {'number': 1, 'status': 'done', 'description': 'Introdução ao golang'},
      {'number': 2, 'status': 'done', 'description': 'A'},
      {'number': 3, 'status': 'done', 'description': 'B'},
      {'number': 4, 'status': 'done', 'description': 'C'},
      {'number': 5, 'status': 'done', 'description': 'D'},
      {'number': 6, 'status': 'done', 'description': 'E'},
      {'number': 7, 'status': 'done', 'description': ''},
      {'number': 8, 'status': 'done', 'description': ''},
      {'number': 9, 'status': 'done', 'description': ''},
      {'number': 10, 'status': 'done', 'description': ''},
      {'number': 11, 'status': 'done', 'description': ''},
      {'number': 12, 'status': 'done', 'description': ''},
      {'number': 13, 'status': 'done', 'description': ''},
      {'number': 14, 'status': 'done', 'description': ''},
      {'number': 15, 'status': 'done', 'description': ''},
      {'number': 16, 'status': 'done', 'description': ''},
      {'number': 17, 'status': 'done', 'description': ''},
      {'number': 18, 'status': 'done', 'description': ''},
      {'number': 19, 'status': 'done', 'description': ''},
      {'number': 20, 'status': 'done', 'description': ''},
      {'number': 21, 'status': 'done', 'description': ''},
      {'number': 22, 'status': 'done', 'description': ''},
      {'number': 23, 'status': 'done', 'description': ''},
      {'number': 24, 'status': 'done', 'description': ''},
      {'number': 25, 'status': 'done', 'description': ''}
    ],
    'status': 'done'
  },
];